<template>
  <v-dialog v-model="dialog" fullscreen hide-overlay transition="dialog-bottom-transition">
    <template v-slot:activator="{ on }">
      <v-btn color="primary" dark outline v-on="on">
        <v-icon left>mdi-plus</v-icon>New Auction
      </v-btn>
    </template>
    <v-card>
      <v-toolbar dark color="primary" dense>
        <v-btn icon dark @click="dialog = false">
          <v-icon>close</v-icon>
        </v-btn>
        <v-toolbar-title>New Auction</v-toolbar-title>
        <v-spacer></v-spacer>
      </v-toolbar>
      <v-card-text>
        <v-subheader>General</v-subheader>
        <v-stepper v-model="stepIdx" vertical>
          <v-stepper-step :complete="stepIdx > 1" step="1">
            Create a Non-fungible token (ERC721 Compilant)
            <small>Create a Deed/Token</small>
          </v-stepper-step>

          <v-stepper-content step="1">
            <v-form @submit="newDeed">
              <v-text-field
                v-model="guid"
                label="Unique ID - Autogenerated (Edit if required)"
                required
              ></v-text-field>
              <v-text-field
                label="DeedURI (ERC721 URI)"
                placeholder="ipfs/swarm or domain.eth"
                required
                v-model="deedURI"
              ></v-text-field>
              <v-btn
                color="primary"
                :outline="deedOK"
                type="submit"
                :disabled="!deedOK"
              >Create Deed/Token</v-btn>
            </v-form>
          </v-stepper-content>

          <v-stepper-step :complete="stepIdx > 2" step="2">
            Transfer ownership of Deed/Token to AuctionRepository
            <small>Transfer Ownership</small>
          </v-stepper-step>

          <transferer/>

          <v-stepper-step :complete="stepIdx > 3" step="3">
            Create an auction
            <small>Enter the details of the auction</small>
          </v-stepper-step>

          <maker :step-idx.sync="stepIdx"/>
        </v-stepper>
      </v-card-text>
    </v-card>
  </v-dialog>
</template>

<script>
import Maker from "./auction/Maker";
import Transferer from "./auction/Transferer";

export default {
  components: { Maker, Transferer },
  data() {
    return {
      auctionTile: null,
      deedIDs: [],
      deedURI: null,
      dialog: true,
      guid: 12345678,
      stepIdx: 2
    };
  },
  computed: {
    deedOK() {
      return !!this.deedURI && !!this.guid;
    }
  },
  methods: {
    newDeed(event) {
      event.preventDefault();

      console.log("hello");
    }
  }
};
</script>